name: Deploy
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          useyarn: true
          username: 'LauraWebdev'
          reponame: 'nft-statements'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
